name: Python Test (Multiple Versions)

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11, 3.12] # List your desired Python versions
    name: Test with Python ${{ matrix.python-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Poetry # Assuming Poetry is your dependency management tool
        uses: Gr1N/setup-poetry@v8

      - name: Install dependencies
        run: poetry install

      - name: Run tests with coverage
        run: make test # Replace with your specific test command if necessary

      - name: SonarCloud Scan (Optional)
        uses: SonarSource/sonarcloud-github-action@master # Adjust version if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        if: ${{ success() }} # Run SonarCloud only on successful test runs
